const shopActionTypes = {
    // UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START: 'FETCH_COLLETIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLETIONS_SUCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLETIONS_FAILURE'
}

export default shopActionTypes;