export const cartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    TOGGLE_DISPLAY: 'TOGGLE_DISPLAY',
    DELETE_ITEM: 'DELETE_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    ADD_CART_COLLECTION: 'ADD_CART_COLECTION',
    SAVE_CART_START: 'FETCH_CART_START',
    SAVE_CART_SUCCESS: 'FETCH_CART_SUCESS',
    SAVE_CART_FAILURE: 'FETCH_CART_FAILURE'
}