export const cartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    TOGGLE_DISPLAY: 'TOGGLE_DISPLAY',
    DELETE_ITEM: 'DELETE_ITEM',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    EMPTY_CART: 'EMPTY_CART'
}